const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
const USER_LOGOUT = "USER_LOGOUT"

const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"
const USER_REGISTER_CLEAR = "USER_REGISTER_CLEAR"

const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST"
const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS"
const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL"
const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET"

export {USER_LOGIN_REQUEST, USER_LOGIN_SUCCESS, USER_LOGIN_FAIL, USER_LOGOUT, 
        USER_REGISTER_REQUEST, USER_REGISTER_SUCCESS, USER_REGISTER_FAIL,
        USER_REGISTER_CLEAR, USER_DETAILS_REQUEST, USER_DETAILS_SUCCESS, 
        USER_DETAILS_FAIL, USER_UPDATE_PROFILE_REQUEST, USER_UPDATE_PROFILE_SUCCESS,
        USER_UPDATE_PROFILE_FAIL, USER_UPDATE_PROFILE_RESET}